---
- name: Configure AWX Standalone Server
  hosts: "{{ awx_single_node }}" 
  gather_facts: true
  become: true
  vars_prompt:

    - name: awx_postgres_db_password
      prompt: "What is the Password for AWX Postgres DB?"
      private: no 

    - name: secret_key
      prompt: "Please enter a secret key to use for Postgres DB encryption"
      private: no 

    - name: awx_admin_username
      prompt: "What is the name of the AWX Admin User?"
      private: no 

    - name: awx_admin_username_password
      prompt: "What is the password for the AWX Admin User?"
      private: no 

  roles:
  
    - install_required_packages
    - install_k3s
    #- certbot_install_for_awx_nodes
    - awx_operator_setup
    - configure_standonlone_awx_server