- name: Generate docker container list for awx-task pod
  ansible.builtin.shell: "docker container ls | grep awx-task"
  args:
    executable: /bin/bash
  register: docker_container_output
  failed_when: docker_container_output.rc ==1

#Need to fix variable docker container List
- name: Get docker container list
  no_log: true
  set_fact:
    docker_container_awx_task_variable_list: "{{ docker_container_output.stdout_lines |  join(',') }}"

#Need to fix variable to remove Unnecessary Info From docker_container_variable List Conversion Pt.1
- name: Editing docker_container_awx_task_variable_list to get awx-task container pod name
  no_log: true
  set_fact:
    awx_task_container_variable: "{{ docker_container_awx_task_variable_list | regex_findall('k8s_.*' ) }}"

- name: Generate docker container list for awx-web pod
  ansible.builtin.shell: "docker container ls | grep awx-web"
  args:
    executable: /bin/bash
  register: docker_container_awx_web_output
  failed_when: docker_container_awx_web_output.rc ==1
  

#Need to fix variable to extra docker container List Conversion
- name: Get docker container list
  no_log: true
  set_fact:
    docker_container_awx_web_variable_list: "{{ docker_container_awx_web_output.stdout_lines |  join(',') }}"

#Need to fix variable to remove Unnecessary Info From  docker_container_awx_web_variable_list Conversion
- name: Editing docker_container_awx_web_variable_list to get awx-web container pod name
  no_log: true
  set_fact:
    awx_web_container_variable: "{{ docker_container_awx_web_variable_list | regex_findall('k8s_.*' ) }}"


- name: Enter docker awx-web container & create super user
  ansible.builtin.shell: "docker cp  /ITS_tools/awx-operator/backup_super_user_creation.sh {{ awx_web_container_variable[0] }}:/ "
  args:
    executable: /bin/bash

- name: Run backup_super_user_creation.sh on AWX Web Container
  ansible.builtin.shell: "docker exec -i {{ awx_web_container_variable[0] }} bash < /ITS_tools/awx-operator/backup_super_user_creation.sh"
  args:
    executable: /bin/bash


- name: Restart AWX Pods
  ansible.builtin.shell: /usr/local/bin/kubectl rollout restart deployment awx
  args:
    executable: /bin/bash
