---
#We will install the nescessary packages required to run 

- name: Include package install
  ansible.builtin.include_tasks:
    file: package_install.yml
  when: ('RedHat' in ansible_os_family )


