#Add Docker Repo
- name: Upgrade Pip
  ansible.builtin.shell: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
  args:
    executable: /bin/bash


- name: Install the Necessary Packages required to run AWX Server
  yum:
    name:
      - git
      - make
      - gcc
      - gcc-c++
      - nodejs
      - gettext
      - device-mapper-persistent-data
      - lvm2
      - bzip2
      - python3-pip
      - libseccomp
      - pam_krb5
      - cyrus-sasl 
      - psmisc 
      - tcpdump 
      - cyrus-sasl-gssapi
      - python3-policycoreutils
      - NetworkManager-cloud-setup
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - setroubleshoot



#Upgrade Pip 
- name: Upgrade Pip
  ansible.builtin.shell: 'pip3 install --upgrade pip'
  args:
    executable: /bin/bash


- name: Install multi python packages
  pip:
    name:
      - cryptography
      - setuptools_rust
      - ansible


#We Will Install all the Development Tools Software
- name: Install Development Tools 
  ansible.builtin.shell: 'yum -y groupinstall "Development Tools"'
  args:
    executable: /bin/bash


- name: Start Docker Service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes