---

- name: Include setup_stand_alone_awx_instance.yml File - ( RHEL Install )
  ansible.builtin.include_tasks:
    file: setup_stand_alone_awx_instance_on_rhel.yml
  when: ('RedHat' in ansible_os_family )


