---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx



secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx_postgres_server
      - port=5432
      - database=awx
      - username=awx
      - password=awx_postgres_db_password
      - type=unmanaged


resources:

  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - awx.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.30.0


